### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-discovery-kubernetes#27]

**Comment by invidian** [comment]
After talking to @roobre, I think the following things should be part of unit tests:
- Connecting to kubelet using kubeconfig (with minikube, this also tests connecting to kubelet with self-signed serving certificate, related to #35).
- ~Connecting to kubelet using service account token (most common scenario).~ This cannot really be tested easily from Go.
- Creating a test pod and verifying all expected fields are populated by kubelet via `/pods` API.
