### ISSUE TITLE
Log discovery output in verbose mode

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-discovery-kubernetes#29]
## Is your feature request related to a problem? Please describe.

When running complex integrations (e.g. Kafka) on top of kubernetes it can be tricky to debug where the problem is, and sometimes it lies in erroneous discovery configuration.

## Feature Description

nri-discovery-kubernetes should log what objects has been discovered (and all their properties) when the infrastructure-agent runs with `verbose: 1`.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
