### ISSUE TITLE
Improve documentation regarding k8s specific Attributes

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/nri-discovery-kubernetes#42]
Improve documentation, in the Readme from this Repo and/or [monitor-services-running-kubernetes]( https://docs.newrelic.com/docs/integrations/kubernetes-integration/link-apps-services/monitor-services-running-kubernetes/#integration-config-links) adding K8s specific attributes like podName.

In this documentation [container-auto-discovery-host-integrations](https://docs.newrelic.com/docs/integrations/host-integrations/installation/container-auto-discovery-host-integrations/) there is only the container related attributes. 

It's hard for users to know which attributes can they get from the discovery in order to compound host names for integrations.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
